# Generated by Django 6.0.4 on 2026-04-16 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='professionals.professionalprofile'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['professional', 'scheduled_at'], name='idx_app_prof_time'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'scheduled_at'], name='idx_app_patient_time'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='idx_app_status'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('professional', 'scheduled_at'), name='uq_professional_slot_once'),
        ),
        migrations.AddIndex(
            model_name='availabilityblock',
            index=models.Index(fields=['professional', 'start_at'], name='idx_block_prof_start'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['professional', 'weekday'], name='idx_slot_prof_day'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['modality'], name='idx_slot_modality'),
        ),
    ]
