# Generated by Django 6.0.4 on 2026-04-16 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id', 'ID'), ('title', 'Title'), ('license', 'License'), ('senescyt', 'Senescyt'), ('other', 'Other')], max_length=30)),
                ('file_path', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'professionals_document',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalVerificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('submitted', 'Submitted'), ('assigned', 'Assigned'), ('comment_added', 'Comment Added'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('correction_requested', 'Correction Requested'), ('suspended', 'Suspended')], max_length=40)),
                ('event_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'professionals_verification_event',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalVerificationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_correction', 'Needs Correction'), ('suspended', 'Suspended')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'professionals_verification_submission',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=120)),
                ('public_profile_enabled', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_correction', 'Needs Correction'), ('suspended', 'Suspended')], default='draft', max_length=30)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('teleconsultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_accepting_patients', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professionals', to='catalogs.specialty')),
            ],
            options={
                'db_table': 'professionals_profile',
            },
        ),
    ]
