# Generated by Django 6.0.4 on 2026-04-16 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='professionalverificationevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_verification_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionalverificationsubmission',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_professional_verification_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionalverificationsubmission',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_submissions', to='professionals.professionalprofile'),
        ),
        migrations.AddField(
            model_name='professionalverificationsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_professional_verification_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionalverificationevent',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='professionals.professionalverificationsubmission'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['verification_status'], name='idx_prof_verify'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['city'], name='idx_prof_city'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['province'], name='idx_prof_province'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['public_profile_enabled'], name='idx_prof_public'),
        ),
        migrations.AddIndex(
            model_name='professionaldocument',
            index=models.Index(fields=['document_type'], name='idx_doc_type'),
        ),
        migrations.AddIndex(
            model_name='professionaldocument',
            index=models.Index(fields=['review_status'], name='idx_doc_review'),
        ),
        migrations.AddIndex(
            model_name='professionalverificationsubmission',
            index=models.Index(fields=['status'], name='idx_verif_status'),
        ),
        migrations.AddIndex(
            model_name='professionalverificationsubmission',
            index=models.Index(fields=['submitted_at'], name='idx_verif_submitted'),
        ),
        migrations.AddConstraint(
            model_name='professionalverificationsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'under_review'])), fields=('professional',), name='uq_prof_verif_open_submission'),
        ),
        migrations.AddIndex(
            model_name='professionalverificationevent',
            index=models.Index(fields=['event_type'], name='idx_verif_event_type'),
        ),
        migrations.AddIndex(
            model_name='professionalverificationevent',
            index=models.Index(fields=['created_at'], name='idx_verif_event_created'),
        ),
    ]
