# Generated by Django 6.0.4 on 2026-04-16 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='professionals.professionalprofile'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['verification_status'], name='idx_prof_verify'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['city'], name='idx_prof_city'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['province'], name='idx_prof_province'),
        ),
        migrations.AddIndex(
            model_name='professionalprofile',
            index=models.Index(fields=['public_profile_enabled'], name='idx_prof_public'),
        ),
        migrations.AddIndex(
            model_name='professionaldocument',
            index=models.Index(fields=['document_type'], name='idx_doc_type'),
        ),
        migrations.AddIndex(
            model_name='professionaldocument',
            index=models.Index(fields=['review_status'], name='idx_doc_review'),
        ),
    ]
