# Generated by Django 6.0.4 on 2026-04-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='office_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
